---
- name: RMP
  hosts: rmp
  tasks:
  - name: command execution for ip address
    command: hostname -i

  - name: tar
    script: ./rmp.sh

  - name: Fetch stuff from the remote and save to local
    synchronize:  src={{ item }} dest=/var/lib/jenkins/workspace/log_rotation/rmp/ mode=pull
    with_items:
         - "/root/log.rmp.*.tar.gz"

